        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 20 15:19:18 2017
        MODULE CHECK_PARMS_H__genmod
          INTERFACE 
            SUBROUTINE CHECK_PARMS_H(PROPS,NPROPS,PARMS,NPARMS,ERROR)
              INTEGER(KIND=4) :: NPROPS
              REAL(KIND=8) :: PROPS(NPROPS)
              REAL(KIND=8) :: PARMS(NPROPS)
              INTEGER(KIND=4) :: NPARMS
              INTEGER(KIND=4) :: ERROR
            END SUBROUTINE CHECK_PARMS_H
          END INTERFACE 
        END MODULE CHECK_PARMS_H__genmod
