        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 20 15:19:18 2017
        MODULE DEFINE_H__genmod
          INTERFACE 
            SUBROUTINE DEFINE_H(NASV)
              INTEGER(KIND=4) :: NASV
            END SUBROUTINE DEFINE_H
          END INTERFACE 
        END MODULE DEFINE_H__genmod
