        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 20 15:19:18 2017
        MODULE UMATISNAN_H__genmod
          INTERFACE 
            SUBROUTINE UMATISNAN_H(CHCKNUM,TESTNAN)
              REAL(KIND=8) :: CHCKNUM
              INTEGER(KIND=4) :: TESTNAN
            END SUBROUTINE UMATISNAN_H
          END INTERFACE 
        END MODULE UMATISNAN_H__genmod
