        !COMPILER-GENERATED INTERFACE MODULE: Fri Jul 21 10:22:14 2017
        MODULE CALC_STATEV_H__genmod
          INTERFACE 
            SUBROUTINE CALC_STATEV_H(STRESS,STATEV,PARMS,NPARMS,NASV,   &
     &NSTATV,DEPS)
              INTEGER(KIND=4) :: NSTATV
              INTEGER(KIND=4) :: NASV
              INTEGER(KIND=4) :: NPARMS
              REAL(KIND=8) :: STRESS(6)
              REAL(KIND=8) :: STATEV(NSTATV)
              REAL(KIND=8) :: PARMS(NPARMS)
              REAL(KIND=8) :: DEPS(6)
            END SUBROUTINE CALC_STATEV_H
          END INTERFACE 
        END MODULE CALC_STATEV_H__genmod
