        !COMPILER-GENERATED INTERFACE MODULE: Fri Jul 21 10:22:14 2017
        MODULE MOVE_EPS_H__genmod
          INTERFACE 
            SUBROUTINE MOVE_EPS_H(DSTRAN,NTENS,DEPS,DEPSV)
              INTEGER(KIND=4) :: NTENS
              REAL(KIND=8) :: DSTRAN(NTENS)
              REAL(KIND=8) :: DEPS(6)
              REAL(KIND=8) :: DEPSV
            END SUBROUTINE MOVE_EPS_H
          END INTERFACE 
        END MODULE MOVE_EPS_H__genmod
