        !COMPILER-GENERATED INTERFACE MODULE: Fri Jul 21 10:22:14 2017
        MODULE UMATISNAN_H__genmod
          INTERFACE 
            SUBROUTINE UMATISNAN_H(CHCKNUM,TESTNAN)
              REAL(KIND=8) :: CHCKNUM
              INTEGER(KIND=4) :: TESTNAN
            END SUBROUTINE UMATISNAN_H
          END INTERFACE 
        END MODULE UMATISNAN_H__genmod
